### ISSUE TITLE
Result VirusTotal

### ISSUE THREAD

**Issue by vanja-san** [AliceorjustAlicia/AllyMods#2]
https://www.virustotal.com/gui/file/d0339fb4795f403fb2f7514709719070ea3d6b1a67c5d2312f2f6f6de790168b/detection

![изображение](https://user-images.githubusercontent.com/7201687/74661014-c1cdfc80-51c9-11ea-9a83-20d335a8b10e.png)

**Comment by AliceorjustAlicia** [comment]
Hello there!

As mentioned afore in another issue that has been opened (https://github.com/AliceorjustAlicia/AllyMods/issues/1), **this project has been obfuscated** with various ways to avoid the spread of my code, but worry not, I have decided to begin a new repository where I am re-coding this program from scratch and with a better code, as I have learned from previous mistakes and gained experience since the start of AllyMods.

In other words, there is no virus, but the obfuscation (encryption of my code) does interfere with the virus scanning as many files across the internet use this method for malicious intent.

For updates on AllyMods 2 (My new open-source mod manager), do refer to the following repository, but keep in mind that it is not yet released.

AllyMods 2: https://github.com/AliceorjustAlicia/AllyMods-2

You are welcome to reply with any inquiries, should you have them.

Have a good one,
Alice.

**Comment by vanja-san** [comment]
Nice, thank you! I a wait! 😊

**Comment by vanja-san** [comment]
Why don't you post your application on this resource? : [modthesims.info](http://modthesims.info)

**Comment by AliceorjustAlicia** [comment]
> Maybe when you release a new version of the app, will you share it on this resource? : [modthesims.info](http://modthesims.info)

I will do so! 😉

**Comment by AliceorjustAlicia** [comment]
> Maybe when you release a new version of the app, will you share it on this resource? : [modthesims.info](http://modthesims.info)

You can now utilize the pre-release of the program, it is fully functional: https://github.com/AliceorjustAlicia/AllyMods-2/releases/tag/Beta

I have queued it on modthesims.info as well :)
